### ISSUE TITLE
Problem with Screen Sharing

### ISSUE THREAD

**Issue by s-ohno-learnie** [AgoraIO/ARD-eEducation-with-Electron#1]
Hi, I am trying release-2.1.0(agora-education-demo 0.2.1) to check screen sharing.

After entering Classroom as a teacher, click "Screen Share" button, my client preview seems to be working, but student side computers cannot see the shared screen, and they get black screen, when teacher click "Screen Share" again(to be off), student side computers see white screen.

Is there any work around for this issue? Or something I need to fix for the code?

Thanks,

**Comment by menthays** [comment]
@s-ohno-learnie 
Thanks for your report. This was a bug in our native sdk and we have fixed it. You can have a try to see if it works.

**Comment by s-ohno-learnie** [comment]
@menthays 

Thank you for your response. I'm looking forward the fix soon.

**Comment by s-ohno-learnie** [comment]
@menthays 

Thanks, I have confirmed the fix, and now the screen sharing works.
