### ISSUE TITLE
agora_node_ext.node is not a valid Win32 application

### ISSUE THREAD

**Issue by KKTVCooling** [AgoraIO/ARD-eEducation-with-Electron#10]
为什么在windows下面启动会报 agora_node_ext.node is not a valid Win32 application 错误？

npm install -D --arch=ia32 electron 执行了也没有用

**Comment by menthays** [comment]
需要在`npm install`后运行`npm install -D --arch=ia32 electron`进行覆盖，之后运行`npm run dev`或者`npm run package-win`应该都是正常的才对。如果仍然不可以，请提供一下详细的信息，比如运行的命令/目录/环境，报错信息，是否变动sdk等。

**Comment by KKTVCooling** [comment]
是按照那个顺序执行的，报AgoraSDK\native-win\agora_node_ext.node is not a valid Win32 application\\错误，sdk并未变动

**Comment by seasun** [comment]
在执行cnpm install 之前，先执行 cnpm install -D --arch=ia32 electron即可，如果不行，删除node_modules再来一次
