### ISSUE TITLE
参数写错了

### ISSUE THREAD

**Issue by sayiwen** [AgoraIO/ARD-eEducation-with-Electron#11]
https://github.com/AgoraIO/ARD-eEducation-with-Electron/blob/a156f7df4cf921c454c3535791039a8630a43372/client/app/AgoraSDK/AgoraSdk.js#L749

除此之外感觉这两个函数没用哦，我服务端录制开启了手动模式。然后再次通过这个函数开始录制但是没有用。

**Comment by menthays** [comment]
这两个native api目前还未完全开放:sleeping:，之后会在js中注释掉。关于录制的实现您可以参考server下的实现。
