### ISSUE TITLE
关于屏幕录制功能

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#12]
你好，我们部署了服务端录制功能，但我们需要做一个录制屏幕（带远近端声音）的录制用于回放，请问这个有什么方法吗？

**Comment by plutoless** [comment]
录制sdk可以录制频道里的所有流，所以只要在频道中分享屏幕流就可以用录制sdk录到了，本地录制暂时还不支持。
