### ISSUE TITLE
信令SDK版本过低

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#14]
我看到agora_sig_sdk.dll的版本是1.2.1，根据你们的发布更新日志 是在1.2.1 版 （发布于 2018 年 3 月 20 日）。
但是很多api没有开放出来，如setAttr,getUserAttr,onUserAttrResult,onMessageSendSuccess等非常重要的API。
请问是不是只是AgoraSig-1.2.1.3.js没做兼容而已，dll其实是通用的，我简单试了下AgoraSig-1.2.1.3.js里的session.socket.on("notify",  function(msg)...
也没发现有这些回调回来

**Comment by plutoless** [comment]
@seasun 我们这里用的是web信令，所以跟dll无关，另外我们信令只用来做频道聊天所以其他功能都没有用到，我们二期会把信令拿掉

**Comment by seasun** [comment]
@plutoless  
嗯，我直接拿websdk的来用也是可以的，你拿掉websdk，那用原生的dll做支持?不可能不用信令的哦
