### ISSUE TITLE
sendStreamMessage 有没有使用案例？

### ISSUE THREAD

**Issue by sayiwen** [AgoraIO/ARD-eEducation-with-Electron#16]
node sdk 里面调用sendStreamMessage 传输了数据但是安卓端没有收到

除此之外，sendStreamMessage 是TCP上传输数据么还是websocket ？

**Comment by menthays** [comment]
- 需要先createDataStream打开数据通道，reliable参数设定为true，我们近期正在补充js文件的注释，具体信息您可以查看AgoraSDK.js中的详细解释
- 信息是随视频流走udp的

**Comment by sayiwen** [comment]
好的，我试试 谢谢啦
