### ISSUE TITLE
Hey, How to compile and run this project

### ISSUE THREAD

**Issue by WildDylan** [AgoraIO/ARD-eEducation-with-Electron#21]

**Comment by WildDylan** [comment]
and about the record server deploy .

**Comment by WildDylan** [comment]
and about the room_control

**Comment by menthays** [comment]
We have [commit](https://github.com/AgoraIO/ARD-eEducation-with-Electron/commit/baca8a2ad4541dbebe96f8f96c05a8bdb94b8e1a) the update of README about deployment of the two service. 

- For recording service, you have to download Agora Recording SDK and put it under /recording. 

- Then just install dependencies of the two services and use [pm2](https://github.com/Unitech/PM2/) to deploy them on your server.

**Comment by WildDylan** [comment]
very thanks

**Comment by WildDylan** [comment]
@menthays questions for choose role: teacher,
always get the Teacher exiest error,

my radata: 

```
[root@devtcpclient radata]# more !
+0#"59894c0c77f74acd81d2f9014419cf01/room1/
+1#"channelStatus.teacher="krsw8tcXrDwPdbEQhu4534136062905
+1#"users.
+2#"19853="krsz53biMUNCR45ntfn534136020102
+2#"55315="krszwem9O7hRW94oha4534136055501
+2#"6
+3#"0415="krt00co01aot3CjJGzqMJb534136060616
+3#"2681="krt024601afwxJjy2sbc0P534136062902
+2#"884709="krsw8tk7UvrJWn1ffea534135884903
+2#"957667="krsxt3hcJecnqg2w7lB534135957900
+0#"jkr
+1#"s
+2#"w8t
+3#"cXrDwPdbEQhu4.
+4#"ts="534136064909534136064909
+4#"u
+5#"id="2681534136062905
+5#"sername="a2q35c4534136062905
+3#"k7UvrJWn1ffea.
+4#"role="teacher534135884903
+4#"username="techer1534135884903
+2#"xt3hcJecnqg2w7lB.
+3#"role="teacher534135957900
+3#"username="techer1534135957900
+2#"z
+3#"53biMUNCR45ntfn.
+4#"role="teacher534136020102
+4#"username="ctecher1534136020102
+3#"wem9O7hRW94oha4.
+4#"role="teacher534136055501
+4#"username="cctecher534136055501
+1#"t0
+2#"0co01aot3CjJGzqMJb.
+3#"role="teacher534136060616
+3#"username="a2q354534136060616
+2#"24601afwxJjy2sbc0P.
+3#"role="teacher534136062902
+3#"username="a2q35c4534136062902
```

how to fix that ? this is my config

```
[root@devtcpclient room_control]# more ecosystem.config.js
module.exports = {
  apps : [{
    name      : 'BarrelService',
    script    : 'server.js',
    env: {
      NODE_ENV: 'development'
    },
    env_production : {
      NODE_ENV: 'production'
    }
  }]

  // deploy : {
  //   production : {
  //     user : 'node',
  //     host : '212.83.163.1',
  //     ref  : 'origin/master',
  //     repo : 'git@github.com:repo.git',
  //     path : '/var/www/production',
  //     'post-deploy' : 'npm install && pm2 reload ecosystem.config.js --env production'
  //   }
  // }
};

need modify this file? 
```

**Comment by WildDylan** [comment]
and my server.js 
```
[root@devtcpclient room_control]# more server.js
const port =
  process.env.PORT ||
  process.argv[2] ||
  9999;
const express = require("express");
const Gun = require("gun");
const app = express();

app.use(Gun.serve);
app.use(express.static(__dirname));

const server = app.listen(port);
Gun({ web: server });
console.log("Server started on port " + port + " with /gun");
```

**Comment by WildDylan** [comment]
`const SERVER_URLS = ["http://112.35.78.57:9999/gun"];`

**Comment by WildDylan** [comment]
<img width="675" alt="default" src="https://user-images.githubusercontent.com/2519544/44013743-10e520de-9efa-11e8-96f3-430a603f5d35.png">

**Comment by WildDylan** [comment]
<img width="857" alt="default" src="https://user-images.githubusercontent.com/2519544/44013801-725e6d2a-9efa-11e8-94b8-18d586aa8c8e.png">

And another problem , login with role: student ,

my words appears twice. ....

**Comment by WildDylan** [comment]
<img width="1024" alt="default" src="https://user-images.githubusercontent.com/2519544/44013932-4f36ce0e-9efb-11e8-8e69-6075033ed834.png">

<img width="800" alt="default" src="https://user-images.githubusercontent.com/2519544/44013933-54b0a18e-9efb-11e8-8c93-9b1308ba909c.png">

<img width="1021" alt="default" src="https://user-images.githubusercontent.com/2519544/44013940-5c54cc76-9efb-11e8-9aaa-9b9965b9edd0.png">

**Comment by menthays** [comment]
第一个老师已存在的问题：

因为当只有一个人在房间并且意外退出（来不及调用leaveClass），此时并没有别人可以监听到并清除掉该用户信息，因此我们推荐加上时间戳作为有效期（实现的时候我们使用十分钟）。

另外，使用gun实现的 data provider 目前阶段仅供参考，实际生产环境中还是推荐别的信令服务（我们的信令/您自己已有的信令服务/socket.io等）自行实现 data provider 模块。

第二个问题：

非常抱歉，我们始终无法复现这个问题:disappointed_relieved:，您可以提供一些更详细的信息么（平台，consolelog等）

**Comment by WildDylan** [comment]
第一个问题，我应该如何修改呢？ 使用的代码是 GIT/ master branch 下的，只修改了 server 的地址。

gun 实现的信令的话，目前是有问题还是说？

第二个问题：我使用学生角色登录进去，打字，出来两遍。 感觉也是 gun 的问题。

因为对 gun 不是很熟悉，还是希望可以得到一个解决方案或者排查错误的方案。 感谢您的回复。

**Comment by menthays** [comment]
1. 登录后没分钟会更新一次老师信息中的ts，然后每次验证如果频道老师信息中的ts距离现在超过十分钟就会算作已过期可以登录，您可以调整这两个时间点。

不推荐直接使用 gun 实现的 data provider 的原因是他太新了，我们主要是作为技术调研使用他，缺少在生产环境中使用的经验。

另外我们测试过，大约只需不到一个下午就可以使用别的技术实现一个data provider实现无副作用的替换（参考signaling data provider），因此你可以很轻松的按照您的技术栈进行替换。

2. 这一个我们默认有打印 [Data Provider] 开头的log，您可以检查控制台中是否确实打印了多个同一条message，如果是的话通过 debug example-data-provider中的emit('message-received')的事件来查看为什么。

**Comment by WildDylan** [comment]
<img width="701" alt="default" src="https://user-images.githubusercontent.com/2519544/44026107-99d6c2ce-9f24-11e8-983b-82a8fe7be18b.png">

这个验证直接去掉可以么？

**Comment by menthays** [comment]
可以的 您可以按照您的业务逻辑来实现 不过注意还是需要resolve 和 reject的

**Comment by WildDylan** [comment]
第二个问题偶现，我现在测试了几遍好像也没有复现出来，我再试试。

**Comment by WildDylan** [comment]
另外还有一个问题，按照文档所说， 打包的win exe打开是白板。

<img width="1034" alt="default" src="https://user-images.githubusercontent.com/2519544/44027860-9455eab8-9f2a-11e8-95b0-a23211becd34.png">

**Comment by menthays** [comment]
去掉验证的话 可能会出现两个老师都加入频道 然后老师的位置显示了两个人这种情况。不过您可以根据业务逻辑自行调整。

您可以参考新的[文档](https://agoraio.github.io/ARD-eEducation-with-Electron)，主要就是需要实现BaseDataProvider这个接口，并且定义一些业务逻辑相关的 action 和 event，目前示例中主要是加入/离开教室，开始/关闭屏幕共享的捕捉，频道消息相关这五个action（参考文档[usage](https://agoraio.github.io/ARD-eEducation-with-Electron/#/en/usage)一节）

**Comment by menthays** [comment]
windows 用户 需要指定安装32位 electron: `npm install -D --arch=ia32 electron` ；
参考 https://agoraio.github.io/ARD-eEducation-with-Electron/#/en/get_started

**Comment by WildDylan** [comment]
恩，在使用 最新版本 cnpm install 之后，run dev 都会出现错误了。。。。 cnpm 很坑爹呀，怎样可以解决一下呢：

mac是这样的：
<img width="1315" alt="default" src="https://user-images.githubusercontent.com/2519544/44068155-4923e3fc-9fab-11e8-89ac-defbdefe28ea.png">

window是这样的错误：

<img width="1210" alt="default" src="https://user-images.githubusercontent.com/2519544/44068212-82a48726-9fab-11e8-9c98-260d7bed5bbe.png">

**Comment by menthays** [comment]
安装依赖过程中应该会从cdn上下载我们编译好的二进制文件才对，会有绿色的成功提示。

可能是在安装一些墙外的包的时候break了整个安装过程。尝试在client目录下添加`.npmrc`文件写入以下内容

```
registry=https://registry.npm.taobao.org
ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/
sass_binary_site=http://npm.taobao.org/mirrors/node-sass
```

然后在client目录下执行`npm install`进行安装（注意这个方法和设置代理的方式冲突，用其中一个就可以了）

**Comment by WildDylan** [comment]
感谢，解决了我的安装依赖的问题。
测试一下打包 window 版本是否可以。

再 macos 上还是可以。于是我装了一台windows的虚拟机并执行

`npm install -D --arch=ia32 electron`

然后打包，终于可以了！！！

@menthays 多谢帮助与支持。

**Comment by WildDylan** [comment]
<img width="800" alt="default" src="https://user-images.githubusercontent.com/2519544/44140496-ceecae5e-a0ac-11e8-8c3b-ab858c36a809.png">

sorry for reopen this issue ....... 
this error occured today ....

**Comment by WildDylan** [comment]
`No ACK received yet.`

**Comment by menthays** [comment]
gun修改数据时没有成功，请检查服务端是否正常，相当于ajax进了catch中

**Comment by WildDylan** [comment]
这个GunServer 怎么看他是不是正常呢。 我启动起来就没碰过他。  pm2 也是 online 正常发自我的iPhone------------------ Original ------------------From: Hao Yang  <notifications@github.com>Date: Wed,Aug 15,2018 5:35 PMTo: AgoraIO/ARD-eEducation-with-Electron <ARD-eEducation-with-Electron@noreply.github.com>Cc: Dylan <dylan@china.com>, State change <state_change@noreply.github.com>Subject: Re: [AgoraIO/ARD-eEducation-with-Electron] Hey, How to compile andrun this project (#21)gun修改数据时没有成功，请检查服务端是否正常，相当于ajax进了catch中

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AgoraIO/ARD-eEducation-with-Electron","title":"AgoraIO/ARD-eEducation-with-Electron","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AgoraIO/ARD-eEducation-with-Electron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@menthays in #21: gun修改数据时没有成功，请检查服务端是否正常，相当于ajax进了catch中"}],"action":{"name":"View Issue","url":"https://github.com/AgoraIO/ARD-eEducation-with-Electron/issues/21#issuecomment-413145732"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AgoraIO/ARD-eEducation-with-Electron/issues/21#issuecomment-413145732",
"url": "https://github.com/AgoraIO/ARD-eEducation-with-Electron/issues/21#issuecomment-413145732",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [AgoraIO/ARD-eEducation-with-Electron] Hey, How to compile and run this project (#21)",
"sections": [
{
"text": "",
"activityTitle": "**Hao Yang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@menthays",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AgoraIO/ARD-eEducation-with-Electron\",\n\"issueId\": 21,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"AgoraIO/ARD-eEducation-with-Electron\",\n\"issueId\": 21\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/AgoraIO/ARD-eEducation-with-Electron/issues/21#issuecomment-413145732"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367374328\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by menthays** [comment]
gun 相当于一个实时的数据库，目前我们还没有处理log相关，会不会是网络原因？一直这样么。

另外验证逻辑最近又做了一些修改，当然您可以直接将验证相关的promise全都弃用来避免 username exists这种报错
