### ISSUE TITLE
当摄像头被占用后，调用startPreview会导致程序闪退且没有日志可捕获

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#4]
![naoixksa5 ukmf s 3 7oo2](https://user-images.githubusercontent.com/1314160/42310683-a30a20e0-806e-11e8-8198-c06cac04c545.png)

用的是最新的demo测试，测试步骤如下：
1。利用别的程序，如QQ占用摄像头；
2. 打开demo程序，此时黑色（正常）；
![image](https://user-images.githubusercontent.com/1314160/42310857-00dede54-806f-11e8-92b0-53c545248e2b.png)
3.进入教室后，再退出再登录就会发生闪退，查看代码是在startPreview后闪退的；

请问这个错误日志怎么才能拿到，或者catch掉，而不是闪退；

**Comment by seasun** [comment]
@menthays 0.4.7
下载地址：https://github.com/AgoraIO/ARD-eEducation-with-Electron/releases，windows sourcecode.
我怀疑是native引发的，但是我不知道在哪能看到日志，electron本身捕捉不了日志信息，只捕获到crash.
请告诉我在哪能看到native的日志吧

**Comment by menthays** [comment]
这应该是我们已修复的问题，然而最近一个月的提交没有打包新的release。 目前已经放出了0.4.8release，相关一系列问题都已修复。
