### ISSUE TITLE
setAudioPlaybackDevice 不起作用

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#5]
你好，setAudioPlaybackDevice 不起作用。
 setAudioPlaybackDevice(deviceid) {
    return this.rtcengine.setAudioPlaybackDevice(deviceid);
  }

对应管网里的这个方法吧
![image](https://user-images.githubusercontent.com/1314160/42356953-ebe4f792-8107-11e8-89bc-9b32e32798bc.png)

![image](https://user-images.githubusercontent.com/1314160/42356929-d74d870e-8107-11e8-888c-1f7727e754bf.png)

![image](https://user-images.githubusercontent.com/1314160/42357242-83d045b0-8109-11e8-82ea-5b96dfdbeee6.png)

**Comment by menthays** [comment]
#4
