### ISSUE TITLE
调用stopAudioPlaybackDeviceTest方法后，setAudioPlaybackVolume与audiodevicevolumechanged的监听都失效了

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#6]
调用stopAudioPlaybackDeviceTest方法后，setAudioPlaybackVolume与audiodevicevolumechanged的监听函数都失效了，只有在播放声音时这两个方法才再次生效

![image](https://user-images.githubusercontent.com/1314160/42377732-23c91d6a-8157-11e8-80df-4e45fa693fef.png)

![image](https://user-images.githubusercontent.com/1314160/42377771-5a597ce4-8157-11e8-9375-c3ec5ff82ce5.png)

**Comment by plutoless** [comment]
@seasun 请提供一下平台信息

**Comment by seasun** [comment]
@plutoless  0.4.7
下载地址：https://github.com/AgoraIO/ARD-eEducation-with-Electron/releases，windows sourcecode.
![image](https://user-images.githubusercontent.com/1314160/42620730-5cc7ba22-85ee-11e8-8358-d8ab6e29f5ac.png)

node --version
v8.11.2

chrome version: 61.0.3163.100

electron version: 2.0.4

**Comment by menthays** [comment]
经查验这是我们native sdk的一个bug，相关工程师正在着手修复。非常感谢您的仔细与热心！

**Comment by seasun** [comment]
@menthays 我们7月底要出第一版，这个来得急吗

**Comment by menthays** [comment]
@seasun 如果比较紧急，请您在客户群中提一下以push一下我们的工程师:sunglasses:，这个项目主要是开源封装的electron sdk的示例项目。
