### ISSUE TITLE
当USB麦克风被拔下时，audiodevicestatechanged回调函数没有被触发

### ISSUE THREAD

**Issue by seasun** [AgoraIO/ARD-eEducation-with-Electron#8]
检测到两个录音设备，当拔下一个时，音频设备变化回调 (onAudioDeviceStateChanged)函数没有被触发，
导致无法重新加载设备，所以也无法指定一个新的deviceID,就没法测试麦克风是否可用。官方demo也有这个问题。
![image](https://user-images.githubusercontent.com/1314160/42384990-29a8b954-816e-11e8-8671-a7043bbcab9f.png)

**Comment by menthays** [comment]
抱歉目前sdk不支持热插拔检测
